### ISSUE TITLE
Respacing

### ISSUE THREAD

**Issue by hz0567** [amanbasu/3d-prostate-segmentation#10]
Hi, thanks for sharing your great work. I am trying to follow your implementation on my own task.  According to your poster, the images are resized and respaced. However, according to the github code, I think you only re-size the MRI images. Am I wrong ? Do I need to further re-space the MRI images  ?

**Comment by amanbasu** [comment]
Respacing is done along with the resizing. You can refer https://github.com/amanbasu/3d-prostate-segmentation/blob/80d46fea6e4e67a639cbd3f4e98280fbdec65d0b/resizing.py#L22

**Comment by hz0567** [comment]
Thanks for your reply. So the spacing can be different for different images ?

**Comment by amanbasu** [comment]
Yes, it will depend on the current size and new size of the image.

**Comment by hz0567** [comment]
Thanks for your help.
