### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by shathaa1983** [amanbasu/3d-prostate-segmentation#11]
Hi, 
thank you for sharing such great work, I am trying to apply your work I faced some issues could you please provide us with simple example or procedure to follow the work and what is expected to see after each step.

Thank you

**Comment by amanbasu** [comment]
Hi! I am not sure what you mean by "simple example or procedure" here.

But, I can list down a rough process you should follow:
1. Download the data from [Promise12](https://promise12.grand-challenge.org).
2. Use [resizing.py](https://github.com/amanbasu/3d-prostate-segmentation/blob/master/resizing.py) to resize all your images to a common shape.
3. Use [train.py](https://github.com/amanbasu/3d-prostate-segmentation/blob/master/train.py) and [predict.py](https://github.com/amanbasu/3d-prostate-segmentation/blob/master/predict.py) to train your model.

**Comment by shathaa1983** [comment]
Thank you for your answer, could you please help me with the tensorflow and python versions you used?

**Comment by shathaa1983** [comment]
Thank you for your answer.
I got this error, could you please help?

![image](https://user-images.githubusercontent.com/69587655/191777060-026d38c2-c91a-4043-8bb3-ec6f9a494ef2.png)

**Comment by amanbasu** [comment]
You probably need to clear the session and start the training again - adam must be already defined in the previous graph.

**Comment by shathaa1983** [comment]
Yes, you alright.

I got another error
![image](https://user-images.githubusercontent.com/69587655/191789833-f33dfcee-817a-47fe-b110-70d2fd742514.png)
 Just a quick notice, I read in the github web site that you mentioned the new image size is (128,128,64) however you defined the new image size in the resizing.py (144,144,50) So which size should I use?

**Comment by amanbasu** [comment]
You can use any. Depending on your GPU memory and batch size.

**Comment by shathaa1983** [comment]
Sounds good

I am trying to solve this error but without luck
![image](https://user-images.githubusercontent.com/69587655/191836283-7d0ef82a-1b8e-4f12-91eb-eeede12b104d.png)

**Comment by amanbasu** [comment]
Did you convert all your images to the same shape?

**Comment by shathaa1983** [comment]
It should be in the resizing.py, right?

**Comment by amanbasu** [comment]
Yes.

**Comment by shathaa1983** [comment]
![image](https://user-images.githubusercontent.com/69587655/192151689-e926c470-aead-4c62-9e9a-660d89098277.png)
I select this new image size for the reshape, but still have the same error. I tried multiple actions but without luck.

**Comment by amanbasu** [comment]
Make sure the you give the correct path to read the images while training. And also verify the image size in the DataGenerator.

**Comment by shathaa1983** [comment]
Ok, I will follow your instructions, could you please provide the python version, TensorFlow version, and other requirements to install?

**Comment by amanbasu** [comment]
Tensorflow 1.10 and python 3.6
