### ISSUE TITLE
Request for model weights

### ISSUE THREAD

**Issue by zwep** [amanbasu/3d-prostate-segmentation#7]
Hi, are you able to upload the model weights as well?

**Comment by amanbasu** [comment]
We deeply regret the unavailability of model weights for the latest version @zwep.
However, I found an unorganized folder containing some weights of the different versions of the model.
[This](https://public-access-folder.s3.ap-south-1.amazonaws.com/model_v6.zip) folder (around 650MB) contains the model code and the checkpoint files, hope they are useful.

**Comment by zwep** [comment]
Ah thanks, will give that one a try!
